# Define available states and cities
states_cities = {
    "New York": [
        "New York City",
        "Buffalo",
        "Rochester",
        "Syracuse",
        "Albany",
        "Saratoga Springs",
        "Schenectady",
        "Suffolk",
        "Yonkers",
        "Syracuse",
        "Saranac Lake",
        "Saratoga Springs",
        "Ithaca",
        "Syracuse",
        "Saranac Lake",
        "Oneonta",
        "Utica",
        "Schenectady",
        "Jamestown",
        "Cooperstown",
    ],
    "California": [
        "Los Angeles",
        "San Francisco",
        "San Diego",
        "San Jose",
        "Sacramento",
        "Fresno",
        "Long Beach",
        "Oakland",
        "Bakersfield",
        "Anaheim",
        "Santa Ana",
        "Riverside",
        "Stockton",
        "Chula Vista",
        "Irvine",
        "Modesto",
        "Santa Clarita",
        "Oxnard",
        "Fontana",
        "Moreno Valley",
        "Glendale",
    ],
    "Florida": [
        "Miami",
        "Orlando",
        "Tampa",
        "Jacksonville",
        "St. Petersburg",
        "Hialeah",
        "Fort Lauderdale",
        "Naples",
        "West Palm Beach",
        "Gainesville",
        "Lakeland",
        "Palm Bay",
        "Melbourne",
        "Cape Coral",
        "Bradenton",
        "Sarasota",
        "Pensacola",
        "Daytona Beach",
        "Ocala",
        "Boca Raton",
    ],
    "Texas": [
        "Houston",
        "Dallas",
        "Austin",
        "San Antonio",
        "Fort Worth",
        "El Paso",
        "Arlington",
        "Corpus Christi",
        "Plano",
        "Laredo",
        "Brownsville",
        "McAllen",
        "Pasadena",
        "Mesquite",
        "Midland",
        "Carrollton",
        "Killeen",
        "Waco",
        "Round Rock",
        "Tyler",
        "Longview",
    ],
    "Illinois": [
        "Chicago",
        "Aurora",
        "Naperville",
        "Joliet",
        "Elgin",
        "Wheaton",
        "Arlington Heights",
        "Skokie",
        "Evanston",
        "Schaumburg",
        "Oak Brook",
        "Oak Lawn",
        "Elmhurst",
        "Downers Grove",
        "Berwyn",
        "Des Plaines",
        "Glenview",
        "Hoffman Estates",
        "Streamwood",
        "Palatine",
    ],
    "Pennsylvania": [
        "Philadelphia",
        "Pittsburgh",
        "Allentown",
        "Erie",
        "Reading",
        "Bethlehem",
        "Lancaster",
        "Harrisburg",
        "York",
        "Scranton",
        "Wilkes-Barre",
        "Lancaster",
        "Chester",
        "Bethlehem",
        "Doylestown",
        "Norristown",
        "Lebanon",
        "Johnstown",
        "Williamsport",
        "State College",
    ],
    "Georgia": [
        "Atlanta",
        "Augusta",
        "Columbus",
        "Savannah",
        "Athens",
        "Macon",
        "Roswell",
        "Marietta",
        "Sandy Springs",
        "Alpharetta",
        "Johns Creek",
        "Gainesville",
        "Dalton",
        "Cumming",
        "Warner Robins",
        "Douglasville",
        "Peachtree City",
        "Newnan",
        "Kennesaw",
        "Acworth",
    ],
    "Washington": [
        "Seattle",
        "Spokane",
        "Tacoma",
        "Vancouver",
        "Bellevue",
        "Kent",
        "Everett",
        "Renton",
        "Redmond",
        "Bellingham",
        "Olympia",
        "Yakima",
        "Kennewick",
        "Richland",
        "Pasco",
        "Pullman",
        "Walla Walla",
        "Mount Vernon",
        "Port Angeles",
        "Quincy",
    ],
    "Massachusetts": [
        "Boston",
        "Worcester",
        "Springfield",
        "Cambridge",
        "Lowell",
        "Brockton",
        "Quincy",
        "Lynn",
        "Newton",
        "Somerville",
        "Lawrence",
        "Haverhill",
        "Fitchburg",
        "Malden",
        "Pittsfield",
        "Framingham",
        "Holyoke",
        "Woburn",
        "Medford",
        "Gloucester",
    ],
    "Ohio": [
        "Columbus",
        "Cleveland",
        "Cincinnati",
        "Toledo",
        "Akron",
        "Dayton",
        "Lorain",
        "Elyria",
        "Youngstown",
        "Mansfield",
        "Canton",
        "Sandusky",
        "Bowling Green",
        "Findlay",
        "Portsmouth",
        "Zanesville",
        "Marietta",
        "Newark",
        "Athens",
        "Westerville",
    ],
    "Michigan": [
        "Detroit",
        "Grand Rapids",
        "Warren",
        "Sterling Heights",
        "Ann Arbor",
        "Lansing",
        "Flint",
        "Dearborn",
        "Livonia",
        "Troy",
        "Westland",
        "Taylor",
        "Royal Oak",
        "Kalamazoo",
        "Port Huron",
        "Saginaw",
        "Midland",
        "Jackson",
        "Traverse City",
        "Muskegon",
    ],
    "Arizona": [
        "Phoenix",
        "Tucson",
        "Mesa",
        "Chandler",
        "Scottsdale",
        "Glendale",
        "Tempe",
        "Peoria",
        "Surprise",
        "Yuma",
        "Casa Grande",
        "Flagstaff",
        "Sierra Vista",
        "Lake Havasu City",
        "Avondale",
        "Goodyear",
        "Buckeye",
        "Maricopa",
        "Apache Junction",
        "Nogales",
        "Show Low",
    ],
    "Colorado": [
        "Denver",
        "Colorado Springs",
        "Aurora",
        "Fort Collins",
        "Boulder",
        "Greeley",
        "Pueblo",
        "Castle Rock",
        "Littleton",
        "Grand Junction",
        "Broomfield",
        "Loveland",
        "Englewood",
        "Arvada",
        "Longmont",
        "Parker",
        "Highlands Ranch",
        "Brighton",
        "Wheat Ridge",
        "Lafayette",
    ],
    "Nevada": [
        "Las Vegas",
        "Henderson",
        "Reno",
        "North Las Vegas",
        "Sparks",
        "Elko",
        "Carson City",
        "Mesquite",
        "Fallon",
        "Ely",
        "Winnemucca",
        "Battle Mountain",
        "Logandale",
        "Silver Springs",
        "Dayton",
        "Pahrump",
        "Fernley",
        "Incline Village",
        "Glenbrook",
        "Yerington",
    ],
    "North Carolina": [
        "Charlotte",
        "Raleigh",
        "Greensboro",
        "Durham",
        "Winston-Salem",
        "Fayetteville",
        "Cary",
        "Gastonia",
        "Burlington",
        "Jacksonville",
        "Huntersville",
        "Mooresville",
        "Apex",
        "Indian Trail",
        "Concord",
        "Salisbury",
        "Wilson",
        "Goldboro",
        "Statesville",
        "Lincolnton",
    ],
    "Virginia": [
        "Virginia Beach",
        "Norfolk",
        "Chesapeake",
        "Richmond",
        "Arlington",
        "Alexandria",
        "Hampton",
        "Newport News",
        "Reston",
        "Lynchburg",
        "Charlottesville",
        "Manassas",
        "Falls Church",
        "Woodbridge",
        "Fredericksburg",
        "Harrisonburg",
        "Blacksburg",
        "Leesburg",
        "Sterling",
        "Vienna",
    ],
    "Maryland": [
        "Baltimore",
        "Columbia",
        "Germantown",
        "Silver Spring",
        "Frederick",
        "Ellicott City",
        "Rockville",
        "Gaithersburg",
        "Hagerstown",
        "Annapolis",
        "Towson",
        "Bel Air",
        "Laurel",
        "Greenbelt",
        "Salisbury",
        "Aberdeen",
        "Catonsville",
        "Odenton",
        "Severn",
        "Upper Marlboro",
    ],
    "New Jersey": [
        "Newark",
        "Jersey City",
        "Paterson",
        "Elizabeth",
        "Edison",
        "Toms River",
        "Hoboken",
        "Bayonne",
        "Perth Amboy",
        "Hackensack",
        "Plainfield",
        "North Bergen",
        "West New York",
        "Clifton",
        "Union City",
        "Somerville",
        "New Brunswick",
        "Bridgeton",
        "Carteret",
        "Dumont",
    ],
    "Oregon": [
        "Portland",
        "Salem",
        "Eugene",
        "Gresham",
        "Hillsboro",
        "Beaverton",
        "Medford",
        "Bend",
        "Grants Pass",
        "Ashland",
        "Roseburg",
        "Klamath Falls",
        "Albany",
        "Corvallis",
        "Tigard",
        "Lake Oswego",
        "Oregon City",
        "Canby",
        "Woodburn",
        "Port Orford",
    ],
    "Minnesota": [
        "Minneapolis",
        "Saint Paul",
        "Rochester",
        "Duluth",
        "Bloomington",
        "Plymouth",
        "Maple Grove",
        "Minnetonka",
        "Eagan",
        "Brooklyn Park",
        "Saint Louis Park",
        "Edina",
        "Shakopee",
        "Moorhead",
        "Faribault",
        "Hastings",
        "Woodbury",
        "Coon Rapids",
        "Burnsville",
        "Roseville",
    ],
    "Wisconsin": [
        "Milwaukee",
        "Madison",
        "Green Bay",
        "Kenosha",
        "Racine",
        "Appleton",
        "Oshkosh",
        "Sheboygan",
        "Waukesha",
        "Eau Claire",
        "Fond du Lac",
        "West Allis",
        "Janesville",
        "Brookfield",
        "Menomonee Falls",
        "Wausau",
        "La Crosse",
        "Plover",
        "New Berlin",
        "Sun Prairie",
    ],
    "Indiana": [
        "Indianapolis",
        "Fort Wayne",
        "Evansville",
        "South Bend",
        "Carmel",
        "Fishers",
        "Muncie",
        "Terre Haute",
        "Anderson",
        "Bloomington",
        "Greenwood",
        "Noblesville",
        "Kokomo",
        "Lawrence",
        "Jeffersonville",
        "Columbus",
        "Westfield",
        "Elkhart",
        "Gary",
        "Richmond",
    ],
    "Missouri": [
        "Kansas City",
        "Saint Louis",
        "Springfield",
        "Columbia",
        "Independence",
        "Lee's Summit",
        "St. Charles",
        "O'Fallon",
        "Blue Springs",
        "Jefferson City",
        "Florissant",
        "Joplin",
        "Kirksville",
        "Cape Girardeau",
        "Maryville",
        "Sullivan",
        "Waynesville",
        "Washington",
        "Sedalia",
        "Moberly",
    ],
    "Iowa": [
        "Des Moines",
        "Cedar Rapids",
        "Davenport",
        "Sioux City",
        "Iowa City",
        "Ames",
        "Waterloo",
        "West Des Moines",
        "Urbandale",
        "Council Bluffs",
        "Dubuque",
        "Mason City",
        "Newton",
        "Fort Dodge",
        "Cedar Falls",
        "Marshalltown",
        "Ottumwa",
        "Burlington",
        "Clinton",
        "Storm Lake",
    ],
    "Kentucky": [
        "Louisville",
        "Lexington",
        "Bowling Green",
        "Owensboro",
        "Covington",
        "Florence",
        "Georgetown",
        "Elizabethtown",
        "Paducah",
        "Frankfort",
        "Hopkinsville",
        "Richmond",
        "Shelbyville",
        "Independence",
        "Harlan",
        "Danville",
        "Madisonville",
        "Ashland",
        "Jackson",
        "Maysville",
    ],
    "Tennessee": [
        "Memphis",
        "Nashville",
        "Knoxville",
        "Chattanooga",
        "Clarksville",
        "Jackson",
        "Murfreesboro",
        "Franklin",
        "Collierville",
        "Brentwood",
        "Johnson City",
        "Hendersonville",
        "Bartlett",
        "Gallatin",
        "Cookeville",
        "Maryville",
        "Kingsport",
        "Lebanon",
        "Sevierville",
        "Somerville",
    ],
    "Alabama": [
        "Birmingham",
        "Montgomery",
        "Mobile",
        "Huntsville",
        "Tuscaloosa",
        "Hoover",
        "Dothan",
        "Auburn",
        "Decatur",
        "Opelika",
        "Florence",
        "Gadsden",
        "Prattville",
        "Bessemer",
        "Selma",
        "Anniston",
        "Cullman",
        "Enterprise",
        "Eufaula",
        "Talladega",
    ],
    "South Carolina": [
        "Charleston",
        "Columbia",
        "Greenville",
        "Myrtle Beach",
        "Spartanburg",
        "Summerville",
        "Hilton Head Island",
        "Rock Hill",
        "Florence",
        "Aiken",
        "Anderson",
        "Goose Creek",
        "Mauldin",
        "Sumter",
        "West Columbia",
        "Orangeburg",
        "Lexington",
        "Easley",
        "Greer",
        "Seneca",
    ],
    "Louisiana": [
        "New Orleans",
        "Baton Rouge",
        "Shreveport",
        "Metairie",
        "Lafayette",
        "Lake Charles",
        "Kenner",
        "Slidell",
        "Houma",
        "Natchitoches",
        "Bossier City",
        "Alexandria",
        "Covington",
        "Morgan City",
        "Minden",
        "Zachary",
        "Opelousas",
        "St. Bernard",
        "Monroe",
        "Ruston",
    ],
    "Arkansas": [
        "Little Rock",
        "Fort Smith",
        "Fayetteville",
        "Springdale",
        "Jonesboro",
        "Pine Bluff",
        "Conway",
        "Bentonville",
        "Hot Springs",
        "El Dorado",
        "Russellville",
        "Sherwood",
        "Cabot",
        "Jacksonville",
        "Bryant",
        "Searcy",
        "Van Buren",
        "Hope",
        "Monticello",
        "Magnolia",
    ],
    "Oklahoma": [
        "Oklahoma City",
        "Tulsa",
        "Norman",
        "Edmond",
        "Moore",
        "Midwest City",
        "Enid",
        "Stillwater",
        "Broken Arrow",
        "Lawton",
        "Mustang",
        "Yukon",
        "Shawnee",
        "Bixby",
        "Owasso",
        "Del City",
        "Sapulpa",
        "Ada",
        "Poteau",
        "Guthrie",
    ],
    "Nebraska": [
        "Omaha",
        "Lincoln",
        "Bellevue",
        "Grand Island",
        "Kearney",
        "Fremont",
        "Hastings",
        "Norfolk",
        "Columbus",
        "North Platte",
        "Papillion",
        "La Vista",
        "Broken Bow",
        "Minden",
        "Crete",
        "Ogallala",
        "Beatrice",
        "Scottsbluff",
        "Seward",
        "Wayne",
    ],
    "South Dakota": [
        "Sioux Falls",
        "Rapid City",
        "Aberdeen",
        "Brookings",
        "Mitchell",
        "Watertown",
        "Yankton",
        "Huron",
        "Pierre",
        "Sturgis",
        "Brandon",
        "Belle Fourche",
        "Box Elder",
        "Custer",
        "Lead",
        "Deadwood",
        "Hill City",
        "Elk Point",
        "Madison",
        "Onida",
    ],
    "North Dakota": [
        "Fargo",
        "Bismarck",
        "Grand Forks",
        "Minot",
        "West Fargo",
        "Williston",
        "Dickinson",
        "Jamestown",
        "Mandan",
        "Devils Lake",
        "Grafton",
        "Bowman",
        "Valley City",
        "Beulah",
        "Rugby",
        "Stanley",
        "Harvey",
        "New Town",
        "McKenzie",
        "Ellendale",
    ],
    "Montana": [
        "Billings",
        "Missoula",
        "Great Falls",
        "Bozeman",
        "Helena",
        "Butte",
        "Kalispell",
        "Havre",
        "Glendive",
        "Miles City",
        "Lewistown",
        "Laurel",
        "Colstrip",
        "Sidney",
        "Whitefish",
        "Polson",
        "Livingston",
        "Anaconda",
        "Shelby",
        "Cut Bank",
    ],
    "Wyoming": [
        "Cheyenne",
        "Casper",
        "Laramie",
        "Gillette",
        "Jackson",
        "Sheridan",
        "Riverton",
        "Rock Springs",
        "Evanston",
        "Rawlins",
        "Cody",
        "Worland",
        "Douglas",
        "Buffalo",
        "Powell",
        "Green River",
        "Lander",
        "Rawlins",
        "Torrington",
        "Pinedale",
    ],
    "Idaho": [
        "Boise",
        "Nampa",
        "Meridian",
        "Idaho Falls",
        "Pocatello",
        "Caldwell",
        "Twin Falls",
        "Coeur d'Alene",
        "Lewiston",
        "Rexburg",
        "Post Falls",
        "Mountain Home",
        "Sandpoint",
        "Jerome",
        "Blackfoot",
        "Kuna",
        "Emmett",
        "Weiser",
        "Moscow",
        "Burley",
    ],
    "Utah": [
        "Salt Lake City",
        "West Valley City",
        "Provo",
        "West Jordan",
        "Orem",
        "Sandy",
        "Ogden",
        "Layton",
        "Midvale",
        "South Jordan",
        "American Fork",
        "Bountiful",
        "Spanish Fork",
        "Tooele",
        "Lehi",
        "St. George",
        "Logan",
        "Draper",
        "Heber City",
        "Eagle Mountain",
    ],
    "Alaska": [
        "Anchorage",
        "Juneau",
        "Fairbanks",
        "Sitka",
        "Ketchikan",
        "Wasilla",
        "Kenai",
        "Palmer",
        "Kodiak",
        "Bethel",
        "Seward",
        "Nome",
        "Barrow",
        "Homer",
        "Unalaska",
        "Petersburg",
        "Cordova",
        "Sand Point",
        "Adak",
        "McGrath",
    ],
    "Hawaii": [
        "Honolulu",
        "Hilo",
        "Kailua",
        "Pearl City",
        "Waipahu",
        "Kaneohe",
        "Mililani Mauka",
        "Kapolei",
        "Ewa Beach",
        "Waianae",
        "Wahiawa",
        "Makakilo",
        "Kahului",
        "Lahaina",
        "Kaanapali",
        "Wailea",
        "Kapalua",
        "Hana",
        "Lihue",
        "Princeville",
    ],
}


neighborhoods = {
    "New York": {
        "New York City": [
            "Manhattan",
            "Brooklyn",
            "Queens",
            "The Bronx",
            "Staten Island",
            "Harlem",
            "SoHo",
            "Greenwich Village",
            "Chelsea",
            "Upper East Side",
            "Upper West Side",
            "East Village",
            "West Village",
            "Midtown",
            "Lower East Side",
            "Financial District",
            "Battery Park City",
            "TriBeCa",
            "Chinatown",
            "Little Italy",
            "Inwood",
            "Washington Heights",
            "Morningside Heights",
            "Yorkville",
            "NoMad",
            "Flatiron District",
            "Gramercy",
            "Hell's Kitchen",
            "NoHo",
            "Flatiron District",
        ],
        "Buffalo": [
            "Allentown",
            "Elmwood Village",
            "North Buffalo",
            "South Buffalo",
            "West Side",
            "University District",
            "Black Rock",
            "Delaware District",
            "Niagara Falls Boulevard",
            "Parkside",
            "Kensington",
            "Central Park",
            "Seneca Street",
            "Old First Ward",
            "Hertel Avenue",
        ],
        "Rochester": [
            "East End",
            "South Wedge",
            "Corn Hill",
            "Charlotte",
            "Irondequoit",
            "Greece",
            "Pittsford",
            "Brighton",
            "Penfield",
            "Webster",
            "Fairport",
            "North Winton Village",
            "Park Avenue",
            "Upper Monroe",
            "South Clinton",
        ],
        "Syracuse": [
            "Downtown",
            "Armory Square",
            "University Hill",
            "Westcott",
            "North Side",
            "Eastwood",
            "South Side",
            "Strathmore",
            "Syracuse University",
            "Historic District",
            "Geddes",
            "Onondaga Hill",
            "Liverpool",
            "Clay",
            "Solvay",
        ],
        "Albany": [
            "Downtown",
            "Pine Hills",
            "Albany City",
            "North Albany",
            "South End",
            "Center Square",
            "West Hill",
            "Helderberg",
            "New Scotland",
            "Delmar",
            "Upper Washington Avenue",
            "South Albany",
            "North End",
            "Loudonville",
            "Colonie",
        ],
        "Saratoga Springs": [
            "Downtown",
            "Broadway",
            "Union Avenue",
            "East Side",
            "West Side",
            "Geyser Crest",
            "Saratoga Lake",
            "Lake Avenue",
            "Congress Park",
            "North Broadway",
            "South Broadway",
            "Wilton",
            "Greenfield Center",
            "Ballston Spa",
            "Milton",
        ],
        "Schenectady": [
            "Downtown",
            "Stockade",
            "Mont Pleasant",
            "Hamilton Hill",
            "Glenville",
            "Niskayuna",
            "Schenectady City",
            "Rotterdam",
            "Delaware Street",
            "Union Street",
            "Liberty Street",
            "Eleventh Street",
            "Fifth Avenue",
            "Central State",
        ],
        "Suffolk": [
            "Huntington",
            "Smithtown",
            "Islip",
            "Babylon",
            "Patchogue",
            "Long Island",
            "Port Jefferson",
            "Lake Ronkonkoma",
            "Sayville",
            "Amityville",
            "Ronkonkoma",
            "West Babylon",
            "East Northport",
            "Copiague",
            "Melville",
        ],
        "Yonkers": [
            "Downtown",
            "Riverdale",
            "South Yonkers",
            "North Yonkers",
            "McLean Avenue",
            "Woodlawn",
            "Glenwood",
            "Bronxville",
            "Greystone",
            "Nepperhan",
            "Tuckahoe Road",
            "Saw Mill River Road",
            "Ludlow",
            "Mount Vernon",
            "Crestwood",
        ],
    },
    "California": {
        "Los Angeles": [
            "Hollywood",
            "Downtown",
            "Santa Monica",
            "Venice",
            "Westwood",
            "Beverly Hills",
            "Silver Lake",
            "Echo Park",
            "Koreatown",
            "Bel-Air",
            "Griffith Park",
            "Mid-Wilshire",
            "Crenshaw",
            "South LA",
            "Studio City",
            "North Hollywood",
            "Mar Vista",
            "West LA",
            "Culver City",
            "Downtown Los Angeles",
            "Arts District",
            "Little Tokyo",
            "Harbor City",
            "San Pedro",
            "Brentwood",
        ],
        "San Francisco": [
            "Financial District",
            "Mission District",
            "SoMa",
            "Chinatown",
            "Castro",
            "Haight-Ashbury",
            "Nob Hill",
            "Tenderloin",
            "Marina District",
            "Noe Valley",
            "Outer Richmond",
            "Outer Sunset",
            "Pacific Heights",
            "Presidio Heights",
            "North Beach",
            "South of Market",
            "Inner Richmond",
            "Inner Sunset",
            "Twin Peaks",
            "Sea Cliff",
            "West of Twin Peaks",
            "Golden Gate Park",
            "Excelsior",
            "Bernal Heights",
            "Glen Park",
        ],
        "San Diego": [
            "Gaslamp Quarter",
            "La Jolla",
            "Pacific Beach",
            "North Park",
            "Hillcrest",
            "Mission Beach",
            "Ocean Beach",
            "Little Italy",
            "Coronado",
            "City Heights",
            "Clairemont",
            "Scripps Ranch",
            "University City",
            "Tierrasanta",
            "Rancho Bernardo",
            "Kearny Mesa",
            "Miramar",
            "Serra Mesa",
            "Carmel Valley",
            "Sorrento Valley",
            "Encinitas",
            "Del Mar",
            "Solana Beach",
            "Carlsbad",
            "Oceanside",
        ],
        "San Jose": [
            "Downtown",
            "Willow Glen",
            "Santana Row",
            "Almaden Valley",
            "Evergreen",
            "Cambrian Park",
            "North San Jose",
            "South San Jose",
            "East San Jose",
            "West San Jose",
            "Rose Garden",
            "Little Italy",
            "Japantown",
            "Berryessa",
            "Guadalupe",
        ],
        "Sacramento": [
            "Downtown",
            "Midtown",
            "East Sacramento",
            "South Sacramento",
            "North Sacramento",
            "Natomas",
            "Arden-Arcade",
            "Land Park",
            "Old Sacramento",
            "Pocket-Greenhaven",
            "Elk Grove",
            "Fair Oaks",
            "Carmichael",
            "Folsom",
            "Roseville",
        ],
        "Fresno": [
            "Downtown",
            "Riverpark",
            "North Fresno",
            "South Fresno",
            "East Fresno",
            "West Fresno",
            "Old Fig Garden",
            "Fig Garden",
            "Roosevelt",
            "Woodward Park",
            "Pinedale",
            "Sunnyside",
            "Clovis",
            "Bullard",
            "Herndon",
        ],
        "Long Beach": [
            "Downtown",
            "Belmont Shore",
            "Bixby Knolls",
            "Lakewood Village",
            "East Village",
            "Naples",
            "South Wrigley",
            "North Long Beach",
            "Alamitos Beach",
            "West End",
            "Signal Hill",
            "Los Altos",
            "Belmont Heights",
            "California Heights",
            "Poly High",
        ],
        "Oakland": [
            "Downtown",
            "Jack London Square",
            "Lake Merritt",
            "Temescal",
            "Fruitvale",
            "West Oakland",
            "Uptown",
            "Glenview",
            "Montclair",
            "North Oakland",
            "Elmhurst",
            "Mosswood",
            "Rockridge",
            "Upper Fruitvale",
            "Eastmont",
        ],
        "Bakersfield": [
            "Downtown",
            "Oildale",
            "Rosedale",
            "Northwest Bakersfield",
            "Southwest Bakersfield",
            "East Bakersfield",
            "South Bakersfield",
            "Olive Drive",
            "The Trails",
            "Stockdale",
            "Seven Oaks",
            "Westchester",
            "Berkshire",
            "Lakeside",
            "Pheasant Run",
        ],
        "Anaheim": [
            "Disneyland",
            "Angel Stadium",
            "GardenWalk",
            "The Colony",
            "Historic District",
            "West Anaheim",
            "East Anaheim",
            "Anaheim Hills",
            "Platinum Triangle",
            "Canyon Hills",
            "Peralta Hills",
            "Kraemer Heights",
            "La Palma",
            "Savi Ranch",
            "North Anaheim",
        ],
    },
    "Florida": {
        "Miami": [
            "Downtown",
            "Wynwood",
            "South Beach",
            "Little Havana",
            "Brickell",
            "Coconut Grove",
            "Coral Gables",
            "Edgewater",
            "Midtown",
            "Wynwood",
            "Aventura",
            "North Miami Beach",
            "Kendall",
            "Design District",
            "Doral",
            "Sunset Harbour",
            "Pinecrest",
            "South Miami",
            "Westchester",
            "The Roads",
        ],
        "Orlando": [
            "Downtown",
            "Lake Eola Heights",
            "College Park",
            "Winter Park",
            "Thornton Park",
            "Baldwin Park",
            "Milk District",
            "South Eola",
            "The Villages",
            "UCF Area",
            "Moss Park",
            "Dr. Phillips",
            "Conway",
            "MetroWest",
            "Windermere",
        ],
        "Tampa": [
            "Downtown",
            "Hyde Park",
            "SoHo",
            "Ybor City",
            "Channelside",
            "Seminole Heights",
            "Carrollwood",
            "Westchase",
            "South Tampa",
            "North Tampa",
            "New Tampa",
            "Tampa Palms",
            "Davis Islands",
            "Temple Terrace",
            "Brandon",
        ],
        "Jacksonville": [
            "Downtown",
            "Riverside",
            "Avondale",
            "Mandarin",
            "San Marco",
            "Springfield",
            "Beaches",
            "Southside",
            "St. Johns",
            "Arlington",
            "Orange Park",
            "Jacksonville Beach",
            "Riverside Avondale",
            "Westside",
            "Northside",
        ],
        "Fort Lauderdale": [
            "Las Olas",
            "Wilton Manors",
            "Victoria Park",
            "Flagler Village",
            "Hollywood",
            "Pine Crest",
            "Coral Ridge",
            "Sunrise",
            "Galt Ocean Mile",
            "Harbor Beach",
            "Imperial Point",
            "Riverwalk",
            "Downtown Fort Lauderdale",
            "Cypress Creek",
            "Lauderdale-by-the-Sea",
        ],
        "West Palm Beach": [
            "Downtown",
            "CityPlace",
            "Clematis Street",
            "Northwood Village",
            "The Acreage",
            "South End",
            "Grandview Heights",
            "El Cid",
            "Lake Worth Beach",
            "Greenacres",
            "Royal Palm Beach",
            "Wellington",
            "Haverhill",
            "Palm Beach",
            "Pine Ridge",
        ],
        "Tallahassee": [
            "Downtown",
            "Killearn Estates",
            "Midtown",
            "Southwood",
            "College Town",
            "The Gables",
            "Capitol Hill",
            "Lake Ella",
            "All Saints District",
            "Bradfordville",
            "Bainbridge",
            "Crawfordville",
            "Woodville",
            "Chaires",
            "Lloyd",
        ],
        "Gainesville": [
            "Downtown",
            "University Heights",
            "Haile Plantation",
            "Tioga",
            "Archer Road",
            "Duckpond",
            "Gainesville Country Club",
            "Kirkwood",
            "Fletcher Park",
            "Gator Nation",
            "Bivens Arm",
            "Eleanor",
            "Wellswood",
            "Tower Road",
            "University Park",
        ],
        "Cape Coral": [
            "Downtown",
            "Cape Harbour",
            "Burnt Store Marina",
            "North Cape Coral",
            "South Cape Coral",
            "Pine Island Road",
            "Sandoval",
            "The Palms",
            "Coral Oaks",
            "Pelican",
            "Trafalgar",
            "Four Freedoms Park",
            "Chiquita Boulevard",
            "Midtown Cape Coral",
            "Lehigh Acres",
        ],
        "Naples": [
            "Old Naples",
            "Pelican Bay",
            "Port Royal",
            "Aqualane Shores",
            "Vanderbilt Beach",
            "Mercato",
            "Park Shore",
            "Golden Gate Estates",
            "East Naples",
            "Lely",
            "Royal Harbor",
            "Naples Park",
            "Lakewood",
            "Quail Creek",
            "Stonebridge",
        ],
    },
}
